export const all_routes = {
  //Home Modules
  // #48 — /home is the canonical landing route; /index still redirects here.
  homeone: "/home",
  hometwo: "/index-2",
  homethree: "/index-3",
  homefour: "/index-4",
  homefive: "/index-5",
  homesix: "/index-6",

  //Course Modules
  // #48 — public course browsing gets clean URLs; the admin-only add/edit
  // screens stay where they are since they aren't public or shareable.
  courseGrid: "/courses",
  courseList: "/courses/list",
  courseDetails: "/courses/details",
  courseDetails2: "/course/course-details-2",
  courseCategory: "/course/course-category",
  courseCategory2: "/course/course-category-2",
  courseCategory3: "/course/course-category-3",
  courseResume: "/course/course-resume",
  courseWatch: "/course/course-watch",
  courseCart: "/course/cart",
  courseCheckout: "/course/checkout",
  addNewCourse: "/course/add-course",
  editCourse: "/course/edit-course",

  //Instructor Modules
  instructorDashboard: "/instructor/instructor-dashboard",
  instructorProfile: "/instructor/instructor-profile",
  instructorCourse: "/instructor/instructor-course",
  instructorCourseGrid: "/instructor/instructor-course-grid",
  instructorAnnouncements: "/instructor/instructor-announcements",
  instructorAssignment: "/instructor/instructor-assignment",
  instructorQuiz: "/instructor/instructor-quiz",
  instructorQuizResult: "/instructor/instructor-quiz-results",
  instructorCertificate: "/instructor/instructor-certificate",
  instructorEarning: "/instructor/instructor-earnings",
  instructorPayout: "/instructor/instructor-payout",
  instructorStatements: "/instructor/instructor-statements",
  instructorMessage: "/instructor/instructor-message",
  instructorTickets: "/instructor/instructor-tickets",
  instructorChangePassword: "/instructor/instructor-change-password",
  instructorPlan: "/instructor/instructor-plans",
  instructorSocialProfiles: "/instructor/instructor-social-profiles",
  instructorLinkedAccounts: "/instructor/instructor-linked-accounts",
  instructorNotification: "/instructor/instructor-notifications",
  instructorIntegrations: "/instructor/instructor-integrations",
  instructorWithdraw: "/instructor/instructor-withdraw",
  instructorWishlist: "/instructor/instructor-withdraw",
  instructorReviews: "/instructor/instructor-withdraw",
  instructorQuizAttempts: "/instructor/instructor-withdraw",
  instructorOrders: "/instructor/instructor-withdraw",
  instructorChat: "/instructor/instructor-withdraw",
  instructorReferral: "/instructor/instructor-withdraw",
  instructorQA: "/instructor/instructor-quiz-questions",
  instructorsettings: "/instructor/instructor-settings",
  approvalScreen: "/instructor/approval-screen",
  allInstructorList: "/instructor/instructor-list",

  // #48 — clean, memorable dashboard routes. The legacy /student/* paths all
  // redirect here (see router.link.tsx), and the student access guard reads
  // these same constants, so the two can't drift apart.
  studentDashboard: "/dashboard",
  studentProfile: "/profile",
  studentsGrid: "/instructor/students",
  studentsDetails: "/instructor/students-details",
  studentsList: "/instructor/student-list",
  studentOrderHistory: "/my-orders",
  // Shop order pipeline. studentMyProducts supersedes studentOrderHistory
  // (which was the template's invented-rows page); the old path stays
  // registered and redirects, so any link already shared keeps working.
  studentMyProducts: "/my-products",
  shopOrderVerification: "/shop/checkout",
  studentMessage: "/messages",
  studentCourses: "/my-courses",
  studentCourseResume: "/my-courses/resume",
  studentCertificates: "/certificates",
  studentReviews: "/student/student-reviews",
  studentWishlist: "/wishlist",
  studentQuiz: "/quizzes",
  studentQuizQuestion: "/quizzes/questions",
  studentReferral: "/student/student-referral",
  studentTickets: "/support-tickets",
  studentSettings: "/student/student-settings",
  studentChangePassword: "/student/student-change-password",
  studentSocialProfile: "/student/student-social-profile",
  studentLinkedAccounts: "/student/student-linked-accounts",
  studentNotification: "/student/student-notifications",
  studentBillingAddress: "/student/student-billing-address",
  studentApprovalScreen: "/student/approval-screen",


  cart: "/cart",
  login: "/login",
  register: "/register",
  forgotpassword: "/forgot-password",
  setpassowrd: "/set-password",
  otp: "/otp",
  lockscreen: "/lock-screen",
  // #48 clean public URLs. These are the canonical paths; the previous
  // /pages/* and /course/* forms are kept as redirects in router.link.tsx so
  // existing links and bookmarks keep working.
  //
  // contactUs previously read "pages/contact-us" with NO leading slash, which
  // React Router treats as RELATIVE — it resolved differently depending on the
  // page you were on. Now absolute like every other route.
  privacyPolicy: "/privacy-policy",
  termsConditions: "/terms",
  contactUs: "/contact",
  about_us: "/about",
  services: "/shop",
  successStories: "/success-stories",
  instructorSuccessStories: "/instructor/instructor-success-stories",
  instructorShop: "/instructor/instructor-shop",
  instructorShopOrders: "/instructor/shop-orders",
  // #47 enrollment + #48 clean routes: the whole 3-step flow stays on /enroll,
  // deep-linked per course via /enroll?course=<id>.
  enroll: "/enroll",
  enrollStatus: "/enroll-status",
  myEnrollments: "/my-enrollments",
  instructorEnrollments: "/instructor/enrollment-requests",
  invoices: "/pages/invoices",
  FAQ: "/pages/faq",
  pricingPlan: "/pages/pricing-plan",
  Error404: "/pages/error-404",
  Error500: "/pages/error-500",
  underconstruction: "/pages/under-construction",
  comingSoon: "/pages/coming-soon",
  becomeAnInstructor: "/pages/become-an-instructor",
  instructorList: "/pages/instructor-list",
  instructorGrid: "/pages/instructor-grid",
  instructorDetails: "/pages/instructor-details",
  notification: "/pages/notifications",
  testimonials: "/pages/testimonials",

  blogGrid: "/blog/blog-grid",
  blogGrid2: "/blog/blog-2-grid",
  blogGrid3: "/blog/blog-3-grid",
  blogDetails: "/blog/blog-details",
  blogCarousal: "/blog/blog-carousal",
  blogMasonry: "/blog/blog-masonry",
  blogLeftSidebar: "/blog/blog-left-sidebar",
  blogRightSidebar: "/blog/blog-right-sidebar",
  blogDetailsLeftSidebar: "/blog/blog-details-left-sidebar",
  blogDetailsRightSidebar: "/blog/blog-details-right-sidebar",
};
